MyShop/MyShop/urls.py
from django.contrib import admin
from django.urls import path, include

from mainapp import views as mainapp

from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path("", mainapp.index, name="main"),
    path("products/", mainapp.products, name='products'),
    path("products/<int:pk>/", mainapp.category, name='category'),
    path("products/<int:pk>/<int:page>/", mainapp.category, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path("contact", mainapp.contact, name = 'contact'),
    path("auth/", include('authapp.urls', namespace = "auth")),
    path("basket/", include('basketapp.urls', namespace = "basket")),
    path('adminka/', include('adminapp.urls', namespace='adminka'))


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyShop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp


app_name = "adminapp"

urlpatterns = [

    path('users/', adminapp.View_Users.as_view(), name='view_users'),
    path('users/<int:page>', adminapp.View_Users.as_view(), name='view_users'),
    path("create_user/", adminapp.Create_User.as_view(), name='create_user'),
    path('update_user/<int:pk>', adminapp.Update_User.as_view(), name='update_user'),
    path('delete_user/<int:pk>', adminapp.delete_user, name='delete_user'),


    path('category/', adminapp.View_Category.as_view(), name='view_category'),
    path("create_category/", adminapp.Create_Category.as_view(), name='create_category'),
    path('update_category/<int:pk>', adminapp.Update_Category.as_view(), name='update_category'),
    path('delete_category/<int:pk>', adminapp.delete_category, name='delete_category'),


    path('<int:pk>/products/', adminapp.view_products, name='view_products'),
    path("create_product/", adminapp.create_product, name='create_product'),
    path('update_product/<int:pk>', adminapp.update_product, name='update_product'),
    path('delete_product/<int:pk>', adminapp.delete_product, name='delete_product'),
]

MyShop/authapp/urls.py
from django.urls import path
import authapp.views as authapp


app_name = "authapp"

urlpatterns = [
    path('login/', authapp.login, name = 'login'),
    path('logout/', authapp.logout, name = 'logout'),
    path('register/', authapp.register, name = 'register'),
    path('edit/', authapp.edit, name = 'edit')
]

MyShop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = "basketapp"

urlpatterns = [
    path('', basketapp.view, name = 'view'),
    path('add/<int:product_id>/', basketapp.add, name = 'add'),
    path('delete/<int:basket_id>/', basketapp.delete, name = 'delete'),
    path('edit/<int:basket_id>/<int:quantity>/', basketapp.edit, name='edit')

]

MyShop/mainapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=25)
    description = models.CharField(max_length=140, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=25)
    description = models.TextField(max_length=140, blank=True)
    image = models.ImageField(upload_to='product_images')
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return self.name

MyShop/mainapp/forms.py
from dataclasses import fields
from django import forms
from .models import Product
from django.forms import ValidationError


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

MyShop/mainapp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
import random
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Product, Category

# Create your views here.

def index(request):
    return render(request, 'mainapp/index.html', context={
        'title': "Главная"
    })

def products(request, page=1):
    products = Product.objects.all()
    categories = Category.objects.all()
    hot_product = random.choice(products)
    products = products.exclude(pk=hot_product.pk)
 
    return render(request, 'mainapp/products.html', context={
        'title': "Продукты",
        'products': products,
        "hot_product":hot_product,
        'categories': categories
    })

def product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = Category.objects.all()
    return render(request, 'mainapp/product.html', context={
        'title': product.name,
        'links_menu': Category.objects.all(),
        'product': product,
        'categories': categories

    })

def category(request, pk, page=1):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=pk)
    products = Product.objects.filter(category=category)
    paginator = Paginator(products, per_page=3)

    if page > paginator.num_pages:
        return HttpResponseRedirect(reverse('category', args=[category.id])) 

    return render(request, 'mainapp/category.html', context={
        'title': "Продукты",
        'products': paginator.page(page),
        'categories': categories,
        "category": category
    })

def contact(request):
    return render(request, 'mainapp/contact.html', context={
        'title': "Контакты"
    })

MyShop/mainapp/templates/mainapp/includes/base.html
{% load static %}
{% load tags %}
<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8">
	<title>{{title}}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

	<link rel="stylesheet" href=" {% static 'font-awesome.css' %}">
</head>
<body>
	<div class="container">
		{% block content %}
        {% endblock %}

		<div class="clr"></div>

	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% current_year %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

</body>
</html>

MyShop/mainapp/templates/mainapp/includes/basket_inc.html
{% load static %}



        {% for item in basket %}
        <div class="basket_record">
            <img src="/media/{{ item.product.image }}"
                 alt="{{ item.product.short_desc }}" class="material-icons">
            <span class="category_name">{{ item.product.category.name }}</span>
            <span class="product_name">{{ item.product.name }}</span>
            <span class="product_price">{{ item.product.price }}&nbspруб</span>
            <input type="number" name="{{ item.pk }}"
                   min="0"
                   value="{{ item.quantity }}">
            <span class="product_cost">{{ item.cost }}&nbspруб</span>
            <button class="btn btn-round">
                <a href="{% url 'basket:delete' item.pk %}" class="error-button pure-button">
                    удалить
                </a>
            </button>
            {% endfor %}
 {% if basket %}
        <br>
        <div class="">
            В корзине {{ request.user.basket.quantity }} товаров общей стоимостью
            {{ request.user.basket.sum }} руб
            <br>
            <br>
        </div>
        {% endif %}

MyShop/mainapp/templates/mainapp/includes/category_inc.html
<div class="links clearfix">
	<ul class="links-menu">
		{% with url_name=request.resolver_match.url_name %}
		{% with category_id=request.resolver_match.kwargs.pk %}
		<li><a href="{% url 'products' %}" class="{% if url_name == 'products' %}active{% endif %}">все</a></li>
		{% for category in categories %}
			<li><a href="{% url 'category' category.id %}" class="{% if url_name == 'category' and category_id == category.id %}active{% endif %}">{{category.name}}</a></li>

		{% endfor %}
		{% endwith %}
		{% endwith %}
	</ul>
</div>

MyShop/mainapp/templates/mainapp/includes/main_manu_inc.html
<div class="header clearfix">
				<a href="/" class="logo"></a>
				<ul class="menu">

					<li><a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %} active {% endif %}">домой</a></li>
					<li><a href="{% url 'products' %}" class="{% if request.resolver_match.url_name == 'products' %} active {% endif %}">продукты</a></li>
					<li><a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %} active {% endif %}">контакты</a></li>
					{% if request.user.is_authenticated %}
					<li><a href = "{% url 'auth:edit'%}">{{user.username}}</a></li>
					<li><a href = "{% url 'basket:view'%}">Корзина ({{request.user.basket.sum}})</a></li>
					{% if request.user.is_superuser %}
					<li><a href = "{% url 'adminka:view_users' %}">Админка</a></li>
					{%endif%}
					<li><a href = "{% url 'auth:logout'%}"> Выйти</a></li>
					{% else %}
					<li><a href = "{% url 'auth:login' %}">Войти </a></li>
					<li><a href = "{% url 'auth:register' %}">Регистрация </a></li>
					{% endif %}
				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>

MyShop/mainapp/templates/mainapp/includes/product_inc.html
{% load static%}

{% for product in products %}
					<div class="block">
						<a href="{% url 'product' product.id %}"><img src="/media/{{ product.image }}" alt="">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>{{product.name}}</h4>
								<p>{{product.description|upper}} </p>
							</div>
						</a>
					</div>
{% endfor %}