MyShop/MyShop/urls.py
from django.contrib import admin
from django.urls import path, include

from mainapp import views as mainapp

from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path("", mainapp.index, name="main"),
    path("products/", mainapp.products, name='products'),
    path("products/<int:pk>/", mainapp.category, name='category'),
    path("products/<int:pk>/<int:page>/", mainapp.category, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path("contact", mainapp.contact, name = 'contact'),
    path("auth/", include('authapp.urls', namespace = "auth")),
    path("basket/", include('basketapp.urls', namespace = "basket")),
    path('adminka/', include('adminapp.urls', namespace='adminka'))


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyShop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp


app_name = "adminapp"

urlpatterns = [

    path('users/', adminapp.View_Users.as_view(), name='view_users'),
    path('users/<int:page>', adminapp.View_Users.as_view(), name='view_users'),
    path("create_user/", adminapp.Create_User.as_view(), name='create_user'),
    path('update_user/<int:pk>', adminapp.Update_User.as_view(), name='update_user'),
    path('delete_user/<int:pk>', adminapp.delete_user, name='delete_user'),


    path('category/', adminapp.View_Category.as_view(), name='view_category'),
    path("create_category/", adminapp.Create_Category.as_view(), name='create_category'),
    path('update_category/<int:pk>', adminapp.Update_Category.as_view(), name='update_category'),
    path('delete_category/<int:pk>', adminapp.delete_category, name='delete_category'),


    path('<int:pk>/products/', adminapp.view_products, name='view_products'),
    path("create_product/", adminapp.create_product, name='create_product'),
    path('update_product/<int:pk>', adminapp.update_product, name='update_product'),
    path('delete_product/<int:pk>', adminapp.delete_product, name='delete_product'),
]

MyShop/adminapp/models.py
from django.db import models

# Create your models here.

MyShop/mainapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=25)
    description = models.CharField(max_length=140, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=25)
    description = models.TextField(max_length=140, blank=True)
    image = models.ImageField(upload_to='product_images')
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return self.name

MyShop/mainapp/forms.py
from dataclasses import fields
from django import forms
from .models import Product
from django.forms import ValidationError


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

MyShop/adminapp/views.py
from django.http.response    import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView
from mainapp.models import Category, Product
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm, ShopUserRegisterForm
from mainapp.forms import ProductForm
from .utils import check_superuser
from django.utils.decorators import method_decorator 


# Create your views here.


class SuperUserRequiredMixin:
    @method_decorator(check_superuser)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class TitleMixin:
    title = None
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.title
        return context
    
    
class View_Users(SuperUserRequiredMixin, TitleMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/view_users.html'
    title = 'Пользователи'
    paginate_by = 2




class Create_User(SuperUserRequiredMixin, TitleMixin, CreateView):
    model = ShopUser
    form_class = ShopUserRegisterForm
    template_name = 'adminapp/create_user.html'
    success_url = reverse_lazy('adminka:view_users')
    title = "Создать пользователя"
    

class Update_User(SuperUserRequiredMixin, TitleMixin, UpdateView):
    model = ShopUser
    template_name = 'adminapp/update_user.html'
    success_url = reverse_lazy('adminka:view_users')
    title = 'Обновить пользователя'
    form_class = ShopUserEditForm


@check_superuser
def delete_user(request, pk):
    user = get_object_or_404(ShopUser,pk=pk)
    user.is_active = False    
    user.save()
    return HttpResponseRedirect(reverse('adminka:view_users'))


class View_Category(SuperUserRequiredMixin, TitleMixin, ListView):
    model = Category
    template_name = 'adminapp/view_category.html'
    title = "Категории"

    
class Create_Category(SuperUserRequiredMixin, TitleMixin, CreateView):
    model = Category
    fields = "__all__"
    template_name = 'adminapp/create_category.html'
    success_url = reverse_lazy('adminka:view_category')
    title = 'Создать категорию'


class Update_Category(SuperUserRequiredMixin, TitleMixin, UpdateView):
    model = Category
    fields = '__all__'
    template_name = 'adminapp/update_category.html'
    success_url = reverse_lazy('adminka:view_category')
    title = 'Обновить категорию'



@check_superuser
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.is_active = False
    category.save()

    return HttpResponseRedirect(reverse("adminka:view_category")) 

@check_superuser
def view_products(request, pk):
    category = Category.objects.get(pk=pk)
    product = Product.objects.filter(category=category)

    return render(request, 'adminapp/view_products.html', context={
        'title':f"Продукты категории {category.name}",
        'products':product,
        'category':category
    })

@check_superuser
def create_product(request):
    form = ProductForm()
    # category = get_object_or_404(Category, pk=category_id)
    if request.method == "POST":
        form = ProductForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("adminka:view_category"))

    return render(request, 'adminapp/create_product.html', context={
        'title':"Cоздания продукта",
        'form':form,
        
    })

@check_superuser
def update_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    form=ProductForm(instance=product)
    if request.method =="POST":
        form = ProductForm(data=request.POST, files=request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('adminka:view_products', args=[product.category.pk]))

    return render(request, 'adminapp/update_product.html', context={
        'title': "Редактирование продукта",
        'form':form,
        'product':product
        
    })

@check_superuser
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    return HttpResponseRedirect(reverse('adminka:view_products', args=[product.category.pk]))

MyShop/mainapp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
import random
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Product, Category

# Create your views here.

def index(request):
    return render(request, 'mainapp/index.html', context={
        'title': "Главная"
    })

def products(request, page=1):
    products = Product.objects.all()
    categories = Category.objects.all()
    hot_product = random.choice(products)
    products = products.exclude(pk=hot_product.pk)
 
    return render(request, 'mainapp/products.html', context={
        'title': "Продукты",
        'products': products,
        "hot_product":hot_product,
        'categories': categories
    })

def product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = Category.objects.all()
    return render(request, 'mainapp/product.html', context={
        'title': product.name,
        'links_menu': Category.objects.all(),
        'product': product,
        'categories': categories

    })

def category(request, pk, page=1):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=pk)
    products = Product.objects.filter(category=category)
    paginator = Paginator(products, per_page=3)

    if page > paginator.num_pages:
        return HttpResponseRedirect(reverse('category', args=[category.id])) 

    return render(request, 'mainapp/category.html', context={
        'title': "Продукты",
        'products': paginator.page(page),
        'categories': categories,
        "category": category
    })

def contact(request):
    return render(request, 'mainapp/contact.html', context={
        'title': "Контакты"
    })

MyShop/mainapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />

    {% block title %}
    <title>{{title}}</title>
    {% endblock %} {% block css%}
    <link
      rel="stylesheet"
      href="https://unpkg.com/purecss@2.1.0/build/pure-min.css"
      integrity="sha384-yHIFVG6ClnONEA5yB5DJXfW2/KC173DIQrYoZMEtBvGzmf0PKiGyNEqe9N6BNDBH"
      crossorigin="anonymous"
    
    />
    <link rel="stylesheet" type="text/css" href="{% static 'my_style.css' %}">
    {% endblock %}
  </head>
  <body>
    
    <div class="h2 text-center head">
      <br>
      <h2>Панель Администратора</h2>
      <br>
    </div>

    <div class="pure-form">
      <button class="btn btn-round">
        <a href="{% url 'main' %}" class="pure-button">на главную</a>
        <a href="{% url 'adminka:view_users' %}" class="pure-button"
          >Пользователи</a
        >
        <a href="{% url 'adminka:view_category' %}" class="pure-button"
          >Категории</a
        >
      </button>
    </div>
    {%block content %} {% endblock %}
  </body>
</html>

MyShop/mainapp/templates/adminapp/create_category.html
{% extends 'adminapp/base.html' %}


{% block content %}
<form class="pure-form" action="{% url 'adminka:create_category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

<br>
    <input class="pure-button pure-button-primary" type="submit" value="Создать Категорию">
</form>
{% endblock %}

MyShop/mainapp/templates/adminapp/create_product.html
{% extends 'adminapp/base.html' %}


{% block content %}
<form class="pure-form" action="{% url 'adminka:create_product' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

<br>
    <input class="pure-button pure-button-primary" type="submit" value="Создать Продукт">
</form>
{% endblock %}

MyShop/mainapp/templates/adminapp/create_user.html
{% extends 'adminapp/base.html' %}


{% block content %}
<form class="pure-form" action="{% url 'adminka:create_user' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

<br>
    <input class="pure-button pure-button-primary" type="submit" value="Создать аккаунт">
</form>
{% endblock %}

MyShop/mainapp/templates/adminapp/update_category.html
{% extends 'adminapp/base.html'%} {%load static%} {% block content%}
<h2>Редактирование Категории</h2>
<form
  action="{% url 'adminka:update_category' object.pk %}"
  enctype="multipart/form-data"
  method="post"
  class="pure-form"
>
  {{form.as_p}} {% csrf_token %}
  <input type="submit" class="pure-button" value="Изменить" />
</form>
{% endblock %}

MyShop/mainapp/templates/adminapp/update_product.html
{% extends 'adminapp/base.html'%} {%load static%} {% block content%}
<h2>Редактирование продукта</h2>
<form
  action="{% url 'adminka:update_product' product.pk %}"
  enctype="multipart/form-data"
  method="post"
  class="pure-form"
>
  {{form.as_p}} {% csrf_token %}
  <input type="submit" class="pure-button" value="Изменить" />
</form>
{% endblock %}

MyShop/mainapp/templates/adminapp/update_user.html
{% extends 'adminapp/base.html'%} {%load static%} {% block content%}
<h2>Редактирование пользователя - {{object.username}}</h2>
<form
  action="{% url 'adminka:update_user' object.pk %}"
  enctype="multipart/form-data"
  method="post"
  class="pure-form"
>
  {{form.as_p}} {% csrf_token %}
  <input type="submit" class="pure-button" value="Изменить" />
</form>
{% endblock %}

MyShop/mainapp/templates/adminapp/view_category.html
{% extends 'adminapp/base.html'%} {%load static%} {% block content%}
<h2>{{title}}</h2>
<div class="pure-form">
    <a href="{% url 'adminka:create_category'%}" class="pure-button">Создать Категорию</a>
    <a href="{% url 'adminka:create_product' %}" class="pure-button">Создать Продукт</a>
    <hr>
  {% for category in object_list %}
  <table class="pure-table pure-table-bordered">
    <thead>
      <tr>
        <th>name</th>
        <th>description</th>
        <th>is_active</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr class="{% if not category.is_active %} inactive {%endif%}" >
        <td>{{category.name}}</td>
        <td>{{category.description}}</td>
        <td>{{category.is_active}}</td>
        <td><a href="{% url 'adminka:view_products' category.pk %}" class="pure-button"
          >К продуктам</a
        ></td>
        <td><a href="{% url 'adminka:update_category' category.pk %}" class="pure-button">Изменить</a></td>
        <td>
          <a
            href="{% url 'adminka:delete_category' category.pk %}"
            class="button-error pure-button"
            >Удалить</a
          >
        </td>
      </tr>
    </tbody>
  </table>
</div>
{%endfor%} {%endblock%}

MyShop/mainapp/templates/adminapp/view_products.html
{% extends 'adminapp/base.html'%} {%load static%} {% block content%}
<h2>{{title}}</h2>
<div class="pure-form">
    <hr>
  {% for product in products %}
  <table class="pure-table pure-table-bordered">
    <thead>
      <tr>
        <th>name</th>
        <th>description</th>
        <th>is_active</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr class="{% if not product.is_active %} inactive {%endif%}" >
        <td>{{product.name}}</td>
        <td>{{product.description}}</td>
        <td>{{product.is_active}}</td>
        <td><a href="{% url 'adminka:update_product' product.pk %}" class="pure-button">Изменить</a></td>
        <td>
          <a
            href="{% url 'adminka:delete_product' product.pk %}"
            class="button-error pure-button"
            >Удалить</a
          
        </td>
      </tr>
    </tbody>
  </table>
</div>
{%endfor%} {%endblock%}

MyShop/mainapp/templates/adminapp/view_users.html
{% extends 'adminapp/base.html'%} {%load static%} {% block content%}
<h2>{{title}}</h2>


<div class="pure-form">
    <a href="{% url 'adminka:create_user'%}" class="pure-button">Создать Пользователя</a>
    <hr>

    {% if page_obj.has_next%}
					<a class="pure-button pure-button-primary" href="{% url 'adminka:view_users' page_obj.next_page_number %}">Cледующая страница</a>
					{% endif %}

					{% if page_obj.has_previous %}
					<a class="pure-button pure-button-primary" href="{% url 'adminka:view_users' page_obj.previous_page_number %}">Предыдущая страница</a>
					{% endif %}
  {% for user in object_list %}
  <table class="pure-table pure-table-bordered">
    <thead>
      <tr>
        <th>username</th>
        <th>last_login</th>
        <th>is_active</th>
        <th>is_superuser</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr class="{% if not user.is_active %} inactive {%endif%}" >
        <td>{{user.username}}</td>
        <td>{{user.last_login}}</td>
        <td>{{user.is_active}}</td>
        <td>{{user.is_superuser}}</td>
        <td><a href="{% url 'adminka:update_user' user.pk %}" class="pure-button">Изменить</a></td>
        <td>
          <a
            href="{% url 'adminka:delete_user' user.pk %}"
            class="button-error pure-button"
            >Удалить</a
          >
        </td>
      </tr>
    </tbody>
  </table>
</div>
{%endfor%} {%endblock%}