MyShop/MyShop/urls.py
from django.contrib import admin
from django.urls import path, include

from mainapp import views as mainapp

from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path("", mainapp.index, name="main"),
    path("products/", mainapp.products, name='products'),
    path("products/<int:pk>/", mainapp.category, name='category'),
    path("products/<int:pk>/<int:page>/", mainapp.category, name='category'),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path("contact", mainapp.contact, name = 'contact'),
    path("auth/", include('authapp.urls', namespace = "auth")),
    path("basket/", include('basketapp.urls', namespace = "basket")),
    path('adminka/', include('adminapp.urls', namespace='adminka'))


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyShop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = "basketapp"

urlpatterns = [
    path('', basketapp.view, name = 'view'),
    path('add/<int:product_id>/', basketapp.add, name = 'add'),
    path('delete/<int:basket_id>/', basketapp.delete, name = 'delete'),
    path('edit/<int:basket_id>/<int:quantity>/', basketapp.edit, name='edit')

]

MyShop/mainapp/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=25)
    description = models.CharField(max_length=140, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=25)
    description = models.TextField(max_length=140, blank=True)
    image = models.ImageField(upload_to='product_images')
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return self.name

MyShop/mainapp/forms.py
from dataclasses import fields
from django import forms
from .models import Product
from django.forms import ValidationError


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

MyShop/mainapp/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
import random
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from .models import Product, Category

# Create your views here.

def index(request):
    return render(request, 'mainapp/index.html', context={
        'title': "Главная"
    })

def products(request, page=1):
    products = Product.objects.all()
    categories = Category.objects.all()
    hot_product = random.choice(products)
    products = products.exclude(pk=hot_product.pk)
 
    return render(request, 'mainapp/products.html', context={
        'title': "Продукты",
        'products': products,
        "hot_product":hot_product,
        'categories': categories
    })

def product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    categories = Category.objects.all()
    return render(request, 'mainapp/product.html', context={
        'title': product.name,
        'links_menu': Category.objects.all(),
        'product': product,
        'categories': categories

    })

def category(request, pk, page=1):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=pk)
    products = Product.objects.filter(category=category)
    paginator = Paginator(products, per_page=3)

    if page > paginator.num_pages:
        return HttpResponseRedirect(reverse('category', args=[category.id])) 

    return render(request, 'mainapp/category.html', context={
        'title': "Продукты",
        'products': paginator.page(page),
        'categories': categories,
        "category": category
    })

def contact(request):
    return render(request, 'mainapp/contact.html', context={
        'title': "Контакты"
    })

MyShop/mainapp/templates/mainapp/category.html
{% extends 'mainapp/includes/base.html' %}
{% load static %}

{% block content %}
	<div class="container">
		<div class="hero-white">
			{% include 'mainapp/includes/main_manu_inc.html' %}
		</div>
		<div class="details">
			{% include 'mainapp/includes/category_inc.html' %}
			<div class="related">
				<div class="title clearfix">
					<h2>{{category}}</h2>
					{% if products.has_next%}
					<a class="explore" href="{% url 'category' category.id products.next_page_number %}">Cледующая страница<img src="{% static 'img/arrow.png' %}" alt=""></a>
					{% endif %}

					{% if products.has_previous %}
					<a class="explore" href="{% url 'category' category.id products.previous_page_number %}">Предыдущая страница<img src="{% static 'img/arrow.png' %}" alt=""></a>
					{% endif %}
				</div>
				<div class="related-products clearfix">
					{% include "mainapp/includes/product_inc.html"%}

				</div>
			</div>
		</div>
{% endblock %}

MyShop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/includes/base.html' %}
{% load static %}

{% block content %}


	<div class="container">
		<div class="hero">
			{% include 'mainapp/includes/main_manu_inc.html' %}
			<h1>наши контакты</h1>
		</div>

		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>

{% endblock %}

MyShop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/includes/base.html' %}
{% load static %}
{% load tags %}


{% block content %}
	<div class="container">
		<div class="slider">
			{% include 'mainapp/includes/main_manu_inc.html' %}
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>

		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				<div class="block">
					<a href="#"><img src="{% static 'img/product-1.jpg' %}"  alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>Отличный стул</h4>
							<p>Расположитесь комфортно. </p>
						</div> 
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/product-2.jpg' %}"  alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>	
			</div>
		</div>
		
{% endblock %}

MyShop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/includes/base.html' %}
{% load static %}

{% block content %}
	<div class="container">
		<div class="hero-white">
			{% include 'mainapp/includes/main_manu_inc.html' %}
		</div>

		<div class="details">
			{% include 'mainapp/includes/category_inc.html' %}

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{{product.image.url}}">
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{product.name}}</h3>
					<p class="price"> {{product.price}} <span>руб</span></p>
					<a href="{% url 'basket:add' product.id %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{product.description|linebreaks}}
					</div>
				</div>
			</div>
{% endblock %}

MyShop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/includes/base.html' %}
{% load static %}

{% block content %}
	<div class="container">
		<div class="hero-white">
			{% include 'mainapp/includes/main_manu_inc.html' %}
		</div>

		<div class="details">
			{% include 'mainapp/includes/category_inc.html' %}

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="{{hot_product.image.url}}">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="{% static 'img/controll.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll1.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="{% static 'img/controll2.jpg' %}" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{hot_product.name}}</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> {{hot_product.price}} <span>руб</span></p>
					<a href="{% url 'basket:add' hot_product.id %}" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						{{hot_product.description|linebreaks}}
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">
					{% include "mainapp/includes/product_inc.html"%}

				</div>
			</div>
		</div>
{% endblock %}